# Site settings
title: Heather Vandervecht
email: heathervandervecht@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Front end developer from London ON who likes learning, space, and Harry Potter. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: _heathervv
github_username:  heathervv

# Build settings
markdown: kramdown

gems:
- jekyll-compass